#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 100
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

counter=1

while [ $counter -le 100 ]

do
  checker3=$((counter % 3))
  checker5=$((counter % 5))

  if [[ $checker3 == 0 ]] && [[ $checker5 == 0 ]]; then
    echo "FizzBuzz"

  elif [[ $checker3 == 0 ]]; then
    echo "Fizz"

  elif [ $checker5 == 0 ]; then
    echo "Buzz"

  else echo "$counter"

  fi

  ((counter += 1))

done
