#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

counter=0

while [ $counter -ne 8 ]
do
   echo "Best School"
   ((counter+=1))

   if [[ $counter == 3 ]]; then
   echo "bad luck"
   fi
   if [[ $counter == 6 ]]; then
   echo "good luck"
   fi
done
