#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

counter=0

while [ $counter -ne 21 ]
do
   ((counter+=1))

   case $counter in

                4)
       echo $counter
       echo "bad luck from china"
       ;;

               9)
       echo $counter
       echo "bad luck from japan"
       ;;

              17)
       echo $counter
       echo "bad luck from Italy"
       ;;

    *)
    echo $counter  
    ;;
   esac
done
