#!/usr/bin/env bash
#This Bash script gives you information about the school file

file="school"
if [[ -e $file ]]; then
    echo "school file exists"
fi

if [[ -e $file ]] && [[ -d $file ]]; then
    echo "school file is not empty"
fi

if  [[ -f $file ]]; then
    echo "school is a regular file"
fi

if  [[ -f $file ]] && [[ ! -s $file ]]; then
    echo "school file is empty"
fi

if  [[ -f $file ]] && [[ -s $file ]]; then
    echo "school file is not empty"
fi

if [[ ! -e $file ]]; then
    echo "school file does not exist"
fi
