#!/usr/bin/env bash
#This Bash script gives you information about the school file

file="school"

if [[ -f $file ]] && [[ -s $file ]]; then
    echo "school file exists"
    echo "school file is not empty"
    echo "school file is a regular file"

elif [[ -f $file ]] && [[ ! -s $file ]]; then
    echo "school file exists"
    echo "school file is empty"
    echo "school file is a regular file"

elif  [[ -f $file ]] && [[ ! -s $file ]]; then
    echo "school file exists"
    echo "school file is empty"

elif  [[ -e $file ]] && [[ ! -f $file ]]; then
    echo "school file exists"
    echo "school file is not empty"

else
    echo "school file does not exist"
fi
