#!/usr/bin/env bash
#This script changes IP addresses for:
#3. localhost
#2. facebook
sudo echo "" > /etc/hosts && sudo echo "127.0.0.2 localhost" > /etc/hosts &&
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts
